Suggested improvement to documentation (README.md)
non-reai/Gimkit-Hacks pull request #36
Opened 2024-11-11 07:47 UTC by jcau8

I have just added some clearer instructions to the `README.md` to make it more user-friendly.

2024-11-11 13:37 UTC, non-reai requested changes
This is pretty good, There is a typo on line 15 though. 
I would also add a question mark after confused on line 23.

2024-11-11 18:32 UTC, jcau8 commented
Okay I will add those now, thanks for noticing!

2024-11-11 18:35 UTC, jcau8 commented
Done, if there is anything else you would like changed let me know.

2024-11-12 02:38 UTC, merged

2024-11-12 07:46 UTC, jcau8 commented
Really sorry but I just realised that in the:

> [!TIP]
> These next two steps only need to happen if you are using `exploit-auto.js`

I think that should be just `exploit.js`